name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 2.2.1
homepage: https://mehran.monster/

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  just_audio: ^0.9.43
  syncfusion_flutter_sliders: ^27.1.57

dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


